# Generated by Django 5.2.4 on 2025-08-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bike",
            options={"verbose_name": "אופניים", "verbose_name_plural": "אופניים"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "לקוח", "verbose_name_plural": "לקוחות"},
        ),
        migrations.AlterModelOptions(
            name="repaircategory",
            options={
                "verbose_name": "קטגורית תיקון",
                "verbose_name_plural": "קטגוריות תיקונים",
            },
        ),
        migrations.AlterModelOptions(
            name="repairitem",
            options={
                "verbose_name": "פריט תיקון",
                "verbose_name_plural": "פריטי תיקון",
            },
        ),
        migrations.AlterModelOptions(
            name="repairjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "תיקון",
                "verbose_name_plural": "תיקונים",
            },
        ),
        migrations.AlterModelOptions(
            name="repairsubcategory",
            options={
                "verbose_name": "תת-קטגורית תיקון",
                "verbose_name_plural": "תת-קטגוריות תיקונים",
            },
        ),
        migrations.AlterModelOptions(
            name="repairupdate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "עדכון תיקון",
                "verbose_name_plural": "עדכוני תיקונים",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "פרופיל משתמש",
                "verbose_name_plural": "פרופילי משתמשים",
            },
        ),
        migrations.AlterField(
            model_name="bike",
            name="brand",
            field=models.CharField(max_length=100, verbose_name="מותג"),
        ),
        migrations.AlterField(
            model_name="bike",
            name="color",
            field=models.CharField(blank=True, max_length=50, verbose_name="צבע"),
        ),
        migrations.AlterField(
            model_name="bike",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bikes",
                to="workshop.customer",
                verbose_name="לקוח",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="model",
            field=models.CharField(blank=True, max_length=100, verbose_name="דגם"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="אימייל"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100, verbose_name="שם"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="טלפון"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="משתמש",
            ),
        ),
        migrations.AlterField(
            model_name="repaircategory",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="שם"),
        ),
        migrations.AlterField(
            model_name="repairitem",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="תאריך ביצוע"
            ),
        ),
        migrations.AlterField(
            model_name="repairitem",
            name="repair_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repair_items",
                to="workshop.repairjob",
                verbose_name="תיקון",
            ),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="אושר בתאריך"
            ),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="assigned_mechanic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_repairs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="מכונאי מוקצה",
            ),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workshop.bike",
                verbose_name="אופניים",
            ),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="נוצר בתאריך"),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="diagnosed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="אובחן בתאריך"
            ),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("reported", "דווח על ידי לקוח"),
                    ("diagnosed", "מאובחן - ממתין לאישור לקוח"),
                    ("partially_approved", "אושר חלקית על ידי לקוח"),
                    ("approved", "אושר על ידי לקוח"),
                    ("in_progress", "בביצוע"),
                    ("awaiting_quality_check", "ממתין לבדיקת איכות"),
                    ("quality_approved", "עבר בדיקת איכות - מוכן לאיסוף"),
                    ("completed", "הושלם"),
                    ("delivered", "נמסר ללקוח"),
                ],
                default="reported",
                max_length=30,
                verbose_name="סטטוס",
            ),
        ),
        migrations.AlterField(
            model_name="repairjob",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                related_name="repair_jobs",
                to="workshop.repairsubcategory",
                verbose_name="תת-קטגוריות",
            ),
        ),
        migrations.AlterField(
            model_name="repairsubcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="workshop.repaircategory",
                verbose_name="קטגוריה",
            ),
        ),
        migrations.AlterField(
            model_name="repairsubcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="שם"),
        ),
        migrations.AlterField(
            model_name="repairupdate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="נוצר בתאריך"),
        ),
        migrations.AlterField(
            model_name="repairupdate",
            name="repair_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="workshop.repairjob",
                verbose_name="תיקון",
            ),
        ),
        migrations.AlterField(
            model_name="repairupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="משתמש",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "לקוח"),
                    ("mechanic", "מכונאי"),
                    ("manager", "מנהל"),
                ],
                default="customer",
                max_length=20,
                verbose_name="תפקיד",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="משתמש",
            ),
        ),
    ]
