# Generated by Django 5.2.4 on 2025-08-20 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_alter_bike_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("approval_needed", "נדרש אישור"),
                            ("ready_for_pickup", "מוכן לאיסוף"),
                            ("repair_update", "עדכון תיקון"),
                            ("new_diagnosis", "אבחון חדש"),
                            ("status_change", "שינוי סטטוס"),
                        ],
                        max_length=20,
                        verbose_name="סוג התראה",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("message", models.TextField(verbose_name="הודעה")),
                (
                    "is_push_sent",
                    models.BooleanField(
                        default=False, verbose_name="הודעת דחיפה נשלחה"
                    ),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך שליחת דחיפה"
                    ),
                ),
                (
                    "is_email_sent",
                    models.BooleanField(default=False, verbose_name="אימייל נשלח"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך שליחת אימייל"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="נקרא")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך קריאה"
                    ),
                ),
                ("is_clicked", models.BooleanField(default=False, verbose_name="נלחץ")),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך לחיצה"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="נוצר בתאריך"),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="כתובת פעולה"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="workshop.customer",
                        verbose_name="לקוח",
                    ),
                ),
                (
                    "repair_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="workshop.repairjob",
                        verbose_name="תיקון",
                    ),
                ),
            ],
            options={
                "verbose_name": "התראת לקוח",
                "verbose_name_plural": "התראות לקוחות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(verbose_name="נקודת קצה")),
                ("p256dh_key", models.TextField(verbose_name="מפתח P256DH")),
                ("auth_key", models.TextField(verbose_name="מפתח Auth")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="סוג מכשיר"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="נוצר בתאריך"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now=True, verbose_name="שימוש אחרון"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="workshop.customer",
                        verbose_name="לקוח",
                    ),
                ),
            ],
            options={
                "verbose_name": "מנוי דחיפה",
                "verbose_name_plural": "מנויי דחיפה",
                "unique_together": {("customer", "endpoint")},
            },
        ),
    ]
