# Generated by Django 5.2.4 on 2025-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_customernotification_pushsubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushsubscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "מנוי להתראות דחיפה",
                "verbose_name_plural": "מנויי התראות דחיפה",
            },
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="last_used_at",
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="failure_count",
            field=models.PositiveIntegerField(default=0, verbose_name="מספר כישלונות"),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="last_failure",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="כישלון אחרון"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="last_success",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="שליחה מוצלחת אחרונה"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="עודכן בתאריך"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.TextField(verbose_name="נקודת קצה"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="סוכן משתמש"),
        ),
    ]
