# Generated by Django for stuck fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_repairitem_block_notes_repairitem_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairjob',
            name='is_stuck',
            field=models.BooleanField(default=False, verbose_name='מכונאי תקוע'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='stuck_reason',
            field=models.TextField(blank=True, verbose_name='סיבת התקיעות'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='stuck_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תאריך סימון כתקוע'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='stuck_resolved',
            field=models.BooleanField(default=False, verbose_name='התקיעות נפתרה'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='manager_response',
            field=models.TextField(blank=True, verbose_name='תגובת מנהל'),
        ),
    ]
