"""
Django settings for garage project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from decouple import config
import shutil

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-$%fb&h2%_kxy_sb4^5oh-qsq)w#xn+io8bfotscgaa=@8&m=2$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)  # זמני לבדיקת שגיאות

ALLOWED_HOSTS = [
    '*',
    'localhost', 
    '127.0.0.1',
    '10.100.102.87',
    '.onrender.com',
    'shai-bike-garage.onrender.com'
]

# CSRF Settings - תיקון בעיות CSRF במעבר בין מכשירים
CSRF_COOKIE_SECURE = not DEBUG  # רק ב-HTTPS בייצור
CSRF_COOKIE_HTTPONLY = False  # מאפשר גישה ל-JavaScript אם נדרש
CSRF_COOKIE_SAMESITE = 'Lax'  # מאפשר CSRF בין תת-דומיינים
CSRF_FAILURE_VIEW = 'workshop.views.csrf_failure'  # Custom CSRF failure handler
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://shai-bike-garage.onrender.com',
    'http://localhost:8000',
    'http://10.100.102.87:8000',
    'http://127.0.0.1:8000',
]

# Session Settings - שיפור יציבות סשן

SESSION_COOKIE_SECURE = False  # רק ב-HTTPS בייצור
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True  # מחדש את הסשן בכל בקשה

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workshop.apps.WorkshopConfig',
    'tailwind',
    'ui',  
    
]

# Push Notification Settings
VAPID_PUBLIC_KEY = "BK7vA-5jG9C3-7Xw9_5vY9_1Y8vJ2G8rZ3L4tE2hQ1mK5dR9_7Xw3V2N5cT8fE9kG2hL6dR7_4Xw1Y8vJ3L5tE9"
VAPID_PRIVATE_KEY = config('VAPID_PRIVATE_KEY', default=None)  # Set this in production
VAPID_CLAIMS = {"sub": "mailto:admin@bike-garage.com"}

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='garage@bike-garage.com')

# Logging for notifications
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'notifications.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'workshop.notification_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
TAILWIND_APP_NAME = 'ui'
INTERNAL_IPS = [
    "127.0.0.1",
    "10.100.102.87",  # Your IP for mobile access
]

NPM_BIN_PATH = shutil.which("npm")

# Debug output (you can remove this later)
if NPM_BIN_PATH:
    print(f"Found npm at: {NPM_BIN_PATH}")
else:
    print("npm not found")



MIDDLEWARE = [
    'workshop.middleware.DatabaseFixMiddleware',  # תיקון אוטומטי של מסד הנתונים
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # עבור קבצים סטטיים ב-production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'garage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'garage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ברירת מחדל SQLite לפיתוח מקומי
default_db_config = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

# ב-production השתמש ב-PostgreSQL מהמשתנה DATABASE_URL
DATABASE_URL = config('DATABASE_URL', default='')
if DATABASE_URL:
    default_db_config = dj_database_url.parse(DATABASE_URL)

DATABASES = {
    'default': default_db_config
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'he'

TIME_ZONE = 'Asia/Jerusalem'

USE_I18N = True

USE_TZ = True

# Locale paths for translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "workshop" / "static",
    BASE_DIR / "ui" / "static",
]

# עבור production - הגדרת תיקיית static root
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise פשוט
WHITENOISE_USE_FINDERS = True

# Force Django admin static files
WHITENOISE_STATIC_PREFIX = '/static/'

# הגדרות אבטחה לproduction
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # שנה
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ...existing code...

# CSRF Settings for Mobile
CSRF_COOKIE_SECURE = False  # Set to True only in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access
CSRF_COOKIE_SAMESITE = 'Lax'  # Better mobile compatibility
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://shai-bike-garage.onrender.com',  # Your production domain
]

# Session settings for mobile
SESSION_COOKIE_SECURE = False  # Set to True only in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True


